# Generated by Django 3.0.2 on 2020-02-13 08:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedtext',
            old_name='text',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='feedimage',
            name='image',
        ),
        migrations.AddField(
            model_name='feedimage',
            name='data',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='file_management.Image'),
        ),
        migrations.AddField(
            model_name='feedread',
            name='read_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shield',
            name='hide_department',
            field=models.BooleanField(default=False),
        ),
    ]
