# Generated by Django 3.0.2 on 2020-02-14 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200214_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedtext',
            name='feed',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='text', to='core.Feed'),
        ),
    ]
