# Generated by Django 3.0.2 on 2020-02-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200214_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchrequest',
            name='matched_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matchrequest',
            name='requested_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
