# Generated by Django 3.0.2 on 2020-02-18 07:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_shield_hide_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='shield',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
