# Generated by Django 3.0.2 on 2020-02-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_shield_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shield',
            name='belong',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shield',
            name='phoneno',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
