# Generated by Django 3.0.2 on 2020-02-18 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0009_auto_20200218_1251'),
        ('core', '0010_like_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='approved_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='declined_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='requestee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_request', to='authorization.IdentityVerification'),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='requestor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_request', to='authorization.IdentityVerification'),
        ),
    ]
