# Generated by Django 3.0.2 on 2020-02-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200218_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchrequest',
            name='date_selected',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchrequest',
            name='max_age',
            field=models.SmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='matchrequest',
            name='min_age',
            field=models.SmallIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='matchrequest',
            name='personnel_selected',
            field=models.SmallIntegerField(default=0),
        ),
    ]
