# Generated by Django 3.0.2 on 2020-02-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200219_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='value',
            field=models.BooleanField(default=True),
        ),
    ]
