# Generated by Django 3.0.2 on 2020-02-21 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0013_identityverification_created_at'),
        ('core', '0014_like_value'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together={('requestee', 'requestor')},
        ),
    ]
