# Generated by Django 3.0.2 on 2020-02-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200221_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='canceled_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
