# Generated by Django 3.0.2 on 2020-02-25 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_friendrequest_canceled_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchrequest',
            name='matched_with',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.MatchRequest'),
        ),
    ]
