# Generated by Django 3.0.2 on 2020-02-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200225_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='canceled_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
