# Generated by Django 3.0.2 on 2020-02-27 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0019_chat_canceled_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='declined_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_recv', to=settings.AUTH_USER_MODEL),
        ),
    ]
