# Generated by Django 3.0.2 on 2020-02-29 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20200227_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chat_type',
            field=models.SmallIntegerField(default=0),
        ),
    ]
