# Generated by Django 3.0.2 on 2020-03-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_chat_chat_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
