# Generated by Django 3.0.2 on 2020-03-02 01:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0022_feed_deleted_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shield',
            unique_together={('user', 'belong'), ('user', 'phoneno')},
        ),
    ]
