# Generated by Django 3.0.2 on 2020-03-02 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20200302_0102'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shield',
            unique_together=set(),
        ),
    ]
