# Generated by Django 3.0.2 on 2020-02-14 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_auto_20200213_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='belongverification',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bv', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='identityverification',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='iv', to=settings.AUTH_USER_MODEL),
        ),
    ]
