# Generated by Django 3.0.2 on 2020-02-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0005_auto_20200217_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='bvimage',
            name='checked_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bvimage',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
