# Generated by Django 3.0.2 on 2020-02-17 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0006_auto_20200217_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='bvimage',
            name='declined_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bvimage',
            name='is_declined',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bvimage',
            name='bv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='authorization.BelongVerification'),
        ),
    ]
