# Generated by Django 3.0.2 on 2020-02-18 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0008_user_hide_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identityverification',
            name='id',
        ),
        migrations.AlterField(
            model_name='identityverification',
            name='phoneno',
            field=models.CharField(max_length=14, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='identityverification',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='iv', to=settings.AUTH_USER_MODEL),
        ),
    ]
