# Generated by Django 3.0.2 on 2020-02-18 14:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0010_auto_20200218_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileimage',
            name='is_main',
        ),
        migrations.AddField(
            model_name='profileimage',
            name='number',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profileimage',
            name='updated_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
