# Generated by Django 3.0.2 on 2020-02-20 18:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0012_auto_20200220_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityverification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
