# Generated by Django 3.0.2 on 2020-02-24 18:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0014_auto_20200222_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='something_with',
            field=models.ManyToManyField(related_name='_user_something_with_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
