# Generated by Django 3.0.2 on 2020-02-25 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0015_user_something_with'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='firebase_token',
        ),
    ]
