# Generated by Django 3.0.2 on 2020-03-01 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0018_auto_20200227_0742'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('code', models.SmallIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authorization.Location'),
        ),
    ]
