# Generated by Django 3.0.2 on 2020-03-02 03:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0019_auto_20200301_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='disconnected_with',
            field=models.ManyToManyField(related_name='_user_disconnected_with_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
